Database system for matches and a few other utilities
dariost/CodeColosseum pull request #2
Opened 2023-06-23 11:46 UTC by z1ko

Hello,

I have implemented a new actor called database which is responsible for saving and retrieving the metadata and history of completed matches. 

```rust
[derive(Debug)]
pub(crate) enum Command {
    /// Request the list of all saved matches ids
    List(oneshot::Sender<Vec<String>>),
    /// Returns the data of a match
    Retrieve {
        // TODO: Can be extendend to support queries
        response: oneshot::Sender<Result<MatchData, DatabaseError>>,
        id: String,
    },
    /// Save a match
    Store(MatchData),
    /// Returns additional data of a match generated by custom tools
    Sync {
        response: oneshot::Sender<Result<Vec<u8>, DatabaseError>>,
        id: String,
        target: String,
    },
}

#[async_trait]
pub(crate) trait Database {
    type Args: Send + 'static;

    fn create(args: Self::Args) -> Self;
    fn close(&mut self);

    async fn execute(&mut self, cmd: Command);
}

pub(crate) fn start<D>(args: D::Args) -> DatabaseHandle
where
    D: Database + Send,
{
    let (tx, mut rx) = mpsc::channel(QUEUE_BUFFER);
    tokio::spawn(async move {
        let mut db = D::create(args);
        info!("Database created");
        loop {
            match rx.recv().await {
                Some(it) => db.execute(it).await,
                _ => break,
            }
        }
        db.close();
        info!("Database closed");
    });

    DatabaseHandle(tx)
}
```

The database interface is agnostic in regard to the storage back-end, for now I have implemented a simple filesystem solution that saves all completed matches data inside a folder with the same name as the id of the match. Everything is inside a root directory, specified using the **COCO_DATABASE_DIR** environment variable.
```rust
let root_dir = std::env::var("COCO_DATABASE_DIR")?;
let db = db::start::<FileSystem>(FileSystemArgs { root_dir });
```

New commands have been added to the client to support database communications:
-  **history**: Allow to retrieve the list of all saved matches
-  **history {flags} [ID]**: Retrieve the saved match data by id and display useful information, like the match history as text as it was shown during play, or a json representation of the match data, useful for pipelining to other tools. 
- **sync [ID] [TargetResource] [OutputPath]**: Download a custom resource from the match, this is useful to retrieve the output of custom tools, for example a tool that renders the history as svg images and places them in a archive inside the match directory.

By request I have also added the flag **--usage** to the list command that allows the client to receive information regarding the usage, description and limits of the custom flags of each game. These are provided by each game builder with the new **get_args_definition** method.

2023-07-01 14:04 UTC, dariost requested changes
Hi,

thank you for your contribution. I've made a first review of the code: while most comments I left are for minor changes, there are some points that we will probably need to discuss, as I see possible pitfalls in their design:

- the specification of game parameters cannot be decoupled from the actual check, since it may lead to the showed description saying one thing, and the code actually doing another;
- the additional tools transformation imho is too generic, as I'm unable to see any use beyond generating the graphics for the history;
- there must be some way of obtaining the additional transformations (or the graphics) of the history while the game is running.

There may be some other minor points that I've addressed in the specific code comments.

2023-07-01 14:04 UTC, dariost commented on src/client.rs
> +    /// List all saved matches
Doesn't this command also output the history for a saved match?

2023-07-01 14:04 UTC, dariost commented on src/client.rs
> +    Sync(SyncCommand),
I'm not sure Sync is the most appropriate command name here

2023-07-01 14:04 UTC, dariost commented on src/client.rs
> +                    println!("{}", value);
In the code base lists are usually printed in a Markdown-like fashion (i.e. items start with a dash)

2023-07-01 14:04 UTC, dariost commented on src/client.rs
> +                    if let Err(e) = std::fs::write(path, data) {
Use the async version of write

2023-07-01 14:04 UTC, dariost commented on src/proto.rs
>  pub(crate) const VERSION: u64 = 1;
The protocol version number should be bumped to 2

2023-07-01 14:04 UTC, dariost commented on src/db/filesystem.rs
> +                let result: Vec<String> = match std::fs::read_dir(&self.args.root_dir) {
Use the async version of read_dir

2023-07-01 14:04 UTC, dariost commented on src/db/filesystem.rs
> +                if let Err(e) = std::fs::create_dir(&match_directory) {
Use the async version of create_dir

2023-07-01 14:04 UTC, dariost commented on src/client.rs
> +                    Err(e) => println!("History error: {:?}", e),
This should be a returned error

2023-07-01 14:04 UTC, dariost commented on src/db/filesystem.rs
> +                println!("{}", input_path);
This should probably be a trace

2023-07-01 14:04 UTC, dariost commented on src/db/filesystem.rs
> +                println!("reading custom resource of match {}: {}", id, target);
This should probably be a trace

2023-07-01 14:04 UTC, dariost commented on src/master.rs
> +    let root_dir = std::env::var("COCO_DATABASE_DIR").unwrap_or_else(|_| {
The database directory should be passed as a command line argument (with a sane default)

2023-07-01 14:04 UTC, dariost commented on src/client.rs
> +                Err(e) => println!("Sync error: {:?}", e),
This should be a returned error

2023-07-01 14:04 UTC, dariost commented on src/client.rs
> +                        println!("Unable to save sync resource: {}", e);
This should be a returned error

2023-07-01 14:04 UTC, dariost commented on src/master.rs
> +        println!(
This should be a warn

2023-07-01 14:04 UTC, dariost commented on src/db/mod.rs
> +pub(crate) struct MatchData {
The match data should also contain the game creation parameters

2023-07-01 14:04 UTC, dariost commented on src/client.rs
> +    #[clap(short, long, help = "Print the match data using json")]
Instead of the direct/json double switch there should probably be a single switch which takes an enum parameter with three options: raw, pretty and json. raw for printing only the history, pretty to print the history with textual meta information (such as the game name, id, players, etc. on the first few lines, and then the history), and json to print the serialized version in json.

2023-07-01 14:04 UTC, dariost commented on src/proto.rs
> +pub(crate) struct GameArgInfo {
While I understand the need for having parameters descriptions, I don't like the fact that they're not enforced (i.e. the declared limits might not match the actually enforced conditions inside the code).

2023-07-01 14:04 UTC, dariost commented on src/game.rs
> +    fn get_args_definition(&self) -> HashMap<String, GameArgInfo>;
This should be async. A game might want to read them from a file. Also, I'd like a more concise function name, such as `args`.

2023-07-01 14:04 UTC, dariost commented on src/games/roshambo/builder.rs
> +        HashMap::new()
The arguments are missing

2023-07-01 14:04 UTC, dariost commented on src/proto.rs
> +    HistoryMatch(Result<MatchData, DatabaseError>),
The match history (and possibly all binary files) should not go through the Text channel of the WebSocket, but on the Binary channel, since the text channel has significant overhead for serialized binary data and has a quite small max message size.

2023-07-01 14:04 UTC, dariost commented on src/proto.rs
> +    SyncFile(Result<Vec<u8>, DatabaseError>),
Same as above (raw data must go on binary channel)

2023-07-01 14:04 UTC, dariost commented on src/db/filesystem.rs
> +                // Apply all post processes
IMHO, the tools that transform the history stream (e.g. the visualizer) should work in a streaming fashion, and should not save on disk their result since it might be several order of magnitudes bigger than the history itself. When the client requires the result of one of this tools. the server should generate it on the fly and send it to the client.

2023-07-01 14:04 UTC, dariost commented on src/client.rs
> +            Command::Sync(cmd) => cmd.run(wsout, wsin).await,
I'm not sure if we really want to support generic transformations of the history, because as far as i know the only use case we really have is to generate the graphics for it. Is there any other possible use case?

2023-07-01 14:04 UTC, dariost commented on src/db/filesystem.rs
> +                let match_directory = format!("{}/{}", self.args.root_dir, &match_data.id);
How do we ensure the uniqueness of the game IDs?

2023-07-03 15:50 UTC, z1ko commented on src/db/filesystem.rs
> +                let match_directory = format!("{}/{}", self.args.root_dir, &match_data.id);
I see that game IDs are randomly generated and a set is used to hold all known IDs at runtime. I propose we switch to UUIDs, that way no special care is required.

2023-07-03 16:47 UTC, z1ko commented on src/proto.rs
> +pub(crate) struct GameArgInfo {
Now GameArgInfo has fields for min and max values that are then used by the builder to check input params correctness.

2023-09-12 19:39 UTC, dariost requested changes
These are the last minor fixes to apply, after that it should be mergeable.

2023-09-12 19:39 UTC, dariost commented on src/db/filesystem.rs
> +            // TODO: Solve path traversal vulnerability
I've just tested it, this vulnerability is present and has to be fixed.

2023-09-12 19:39 UTC, dariost commented on src/db/filesystem.rs
> +                // TODO: Here you apply custom post process tools to generate batch resources
Post processing has been postponed, remove mentions to it.

2023-09-12 19:39 UTC, dariost commented on src/db/filesystem.rs
> +            // TODO: Solve path traversal vulnerability
Again, solve this.

2023-09-12 19:39 UTC, dariost commented on src/db/mod.rs
> +        // TODO: Can be extendend to support queries
You can remove it, for now it's enough.

2023-09-12 19:39 UTC, dariost commented on src/master.rs
> +    if let Err(e) = std::fs::create_dir_all(&root_dir) {
Must use async version.

2023-09-13 16:03 UTC, dariost approved these changes

2023-09-13 16:08 UTC, merged