Gioco Dama
dariost/CodeColosseum pull request #3
Opened 2023-08-07 10:25 UTC by Lorenzo1997

Multiplayer 2v2
Single player contro il bot
Documentazione gioco

2023-09-19 17:41 UTC, dariost requested changes
Faccio un po' di commenti generali perché ci sono cose che si ripetono più volte:

- la rappresentazione interna dello stato è molto strana (usi un char al posto di un enum), e porta a scrivere codice che è molto poco idiomatico;
- l'interazione è più quella che ti aspetteresti con un umano che con un programma, in particolare esula dagli standard posti dagli altri giochi già implementati;
- una cosa fondamentale che non deve mai fare il manager (e speranzosamente anche il bot) è crashare, ma nel codice ci sono svariati punti dove il programma può andare in panic (vedesi tutti gli unwrap).

Come requisito minimo per mergiare questa PR in un branch di staging ti chiedo di risolvere i commenti puntuali che ho fatto e di risolvere almeno il terzo punto generale (quindi levare tutti gli unwrap, gestendo gli errori nei casi in cui possono capitare, e sostituendolo con expect nei casi in cui matematicamente non può crashare).

2023-09-19 17:41 UTC, dariost commented on src/games/dama/instance.rs
> +        // Inizzia sempre la partita il secondo giocatore che si conette
Inizzia -> Inizia

2023-09-19 17:41 UTC, dariost commented on src/games/dama/instance.rs
> +                if &giocatore[1].name == "ServerBot$0"
Non puoi assumere che il bot si chiami sempre in quel modo

2023-09-20 11:34 UTC, Lorenzo1997 commented
Correzioni apportate:
1- Sostituiti tutti gli unwrap con expect
2- Corretto errore di ortografia
3- Ottimizzato il controllo di chi deve muovere le pedine tra bot e player

2023-09-20 16:12 UTC, dariost commented on src/games/dama/logic.rs
> +        giocatore.input.read_line(&mut percorso).await.expect("Lettura della riga fallita !!!");
Questa lettura può fallire, e va gestita

2023-09-20 16:16 UTC, dariost commented on src/games/dama/instance.rs
> +                if giocatore[0].name.starts_with("ServerBot$")
Non puoi assumere niente sul bot, per te deve essere come un qualunque altro giocatore. Chi è il bianco e chi è il nero deve essere o determinato in modo random e comunicato ai giocatori, oppure scelto tramite un qualche parametro a priori.

2023-10-01 10:18 UTC, Lorenzo1997 commented
Sono stati corretti tutti i punti come richiesto.

2023-10-11 10:53 UTC, Lorenzo1997 commented
Correzione del bot terminata.

2023-10-27 10:12 UTC, Lorenzo1997 commented
Aggiornamento del repo e correzioni codice fatte

2023-10-28 00:47 UTC, dariost commented
This PR has been squash-merged in commit f60a9503a97e5bbab8c60e27abbcdccb854ec845

2023-10-28 00:47 UTC, closed without merging